name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
    - name: wait for other runs to finish
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: do deployment using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/webserver/mgmt-ui-web-app
          git fetch --all
          git reset --hard origin/master
          cd frontend
          npm install
          npm run generate
          cd ../backend
          npm install
          npm run build
          forever stop dist/app.js
          forever start dist/app.js
